# Port pre MQTT (pre ESP32 a Backend)
listener 1883
allow_anonymous true

# Port pre WebSockets (pre SvelteKit frontend v reálnom čase)
listener 9001
protocol websockets

# Ukladanie dát
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
