listener 1883 0.0.0.0

# Zakázanie anonymného prístupu
allow_anonymous false
# Port pre WebSockets (pre SvelteKit frontend v reálnom čase)
listener 9001
protocol websockets

# Ukladanie dát
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Nastavenie užívateľov a hesiel
password_file /mosquitto/config/passwords.txt