version: '3.8'

services:
  # 1. Databáza (Mongo)
  db:
    image: mongo:latest
    container_name: sensor_db
    restart: always
    ports:
      - "27018:27017" # Prístup z Windowsu (Compass) cez 27018
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - sensor-network

  # 2. Backend (Express)
  api:
    build: ./backend
    container_name: sensor_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}

      - MQTT_BROKER_URL=${MQTT_BROKER_URL}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    depends_on:
      - db
      - mosquitto
    networks:
      - sensor-network

  # 3. Frontend (SvelteKit)
  web:
    build: ./frontend
    container_name: sensor_web
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Prehliadač teraz volá verejnú Cloudflare adresu - produkcia
      #- PUBLIC_API_URL=https://api.sahur.sk/api
      # Pre testovanie a vývoj, keď beží všetko lokálne, môžeme použiť internú Docker sieť
      - PUBLIC_API_URL=http://localhost:5000/api
      # SvelteKit server (SSR) stále volá backend interne cez Docker sieť
      - INTERNAL_API_URL=http://sensor_api:5000/api
    depends_on:
      - api
    networks:
      - sensor-network

  # 4. MQTT Broker (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"   # MQTT port
      - "9001:9001"   # WebSockets port
    volumes:
      # Namontujeme celý config priečinok
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - sensor-network
  # tunnel:
  #   container_name: cloudflared-tunnel
  #   image: cloudflare/cloudflared:latest
  #   restart: always
  #   environment:
  #     - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
  #   command: tunnel run
  #   depends_on:
  #     - api  # Tunel sa spustí až keď beží backend
  #   networks:
  #     - sensor-network

networks:
  sensor-network:
    driver: bridge