version: '3.8'

services:
  # 1. Databáza (Mongo)
  db:
    image: mongo:latest
    container_name: sensor_db
    ports:
      - "27018:27017" # Prístup z Windowsu (Compass) cez 27018
    volumes:
      - ./mongodb_data:/data/db

  # 2. Backend (Express)
  api:
    build: ./backend
    container_name: sensor_api
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
    depends_on:
      - db
      - mosquitto

  # 3. Frontend (SvelteKit)
  web:
    build: ./frontend
    container_name: sensor_web
    ports:
      - "5173:5173"
    environment:
      # Pre prehliadač (klient): Volá Windows port
      - PUBLIC_API_URL=http://192.168.1.175:5000/api
      # Pre SvelteKit server (SSR): Volá vnútorný Docker názov "api"
      - INTERNAL_API_URL=http://api:5000/api
    depends_on:
      - api

  # 4. MQTT Broker (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"   # MQTT port
      - "9001:9001"   # WebSockets port
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      